# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  tests:

    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    - uses: ./.github/actions/prepare-deps
    - name: Run nox
      run: |
        uvx nox
    - name: Check pip-compile
      run: |
        cp requirements.txt requirements.old.txt
        uv pip compile pyproject.toml -o requirements.txt
        diff requirements.old.txt requirements.txt
        rm requirements.old.txt
    - name: Build
      run: |
        uvx flit build --no-use-vcs
